language: python
python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.4"
  - "3.5"
install:
  - pip install coveralls tox
  - python setup.py install
script:
  - tox
  - coverage run setup.py test
after_success:
  - coveralls
